name: icon-smoke

on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  smoke:
    timeout-minutes: 15
    concurrency:
      group: icon-smoke-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pure-admin-thin-max-ts

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: 'pure-admin-thin-max-ts/.nvmrc'
          check-latest: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Get pnpm store path
        id: pnpm-store
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 预先恢复 Playwright 浏览器缓存，加速后续安装
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-ms-playwright-${{ hashFiles('pure-admin-thin-max-ts/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-ms-playwright-

      # 仅安装 Chromium 并包含依赖（package.json 的 test:install 已限定为 chromium）
      - name: Install Playwright browsers (Chromium only, with deps)
        run: pnpm test:install

      - name: Run icon smoke tests (Chromium)
        env:
          CI: 'true'
          # Playwright 在 CI 下使用 vite preview，默认端口为 4173
          BASE_URL: 'http://127.0.0.1:4173'
        run: pnpm test:icon:smoke

      - name: Upload Playwright HTML report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: pure-admin-thin-max-ts/playwright-report
          if-no-files-found: ignore

      - name: Upload Playwright traces and results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: |
            pure-admin-thin-max-ts/test-results
          if-no-files-found: ignore
